### ISSUE TITLE
Global (for all screens) procedures and variables

### ISSUE THREAD

**Issue by palivoda** [AppyBuilder/IssueTracker#39]
Until this is implemented code reuse is at very low level, in each screen user have to repeat same blocks. 

For example global procedure can be used to call web component to load data from server. During call auth token or user id will be added to URL. 

Also global procedures will help to reduce blocks size and move all routine ouside screen blocks. 

If global procedures could be exported then it could be a kind of library to share.

**Comment by Amerkashi** [comment]
Each screen is independent of other screens and you won't be able to share procedures (blocks).
