### ISSUE TITLE
OneSignalPush

### ISSUE THREAD

**Issue by Amerkashi** [AppyBuilder/IssueTracker#8]
OneSignalPush is not working for Android 8
![image](https://user-images.githubusercontent.com/36113589/44127654-558e23bc-a00c-11e8-85e6-b88aea0b70e2.png)

**Comment by Amerkashi** [comment]
Forum post here:

https://community.appybuilder.com/t/one-signal-error-on-android-8/13269/8

**Comment by jcoleman2005** [comment]
Merged into October 13, 2018 release
